### ISSUE TITLE
Incorrect logic in setup-convert2rhel.yml when skip_os_version_check is true

### ISSUE THREAD

**Issue by steven-ellis** [oamg/convert2rhel#532]
In the OS Validation section  it isn't possible to skip the check due to the current logic
```
    - name: Validate Release Version (6.10, 7.9, 8.5)
      fail:
        msg: "Distribution version must be 6.10, 7.9, or 8.5"
      when: (ansible_distribution_version != '6.10' and ansible_distribution_version != '7.9'
             and ansible_distribution_version != '8.5') or skip_os_version_check|bool
```

Should be

```
    - name: Validate Release Version (6.10, 7.9, 8.5)
      fail:
        msg: "Distribution version must be 6.10, 7.9, or 8.5"
      when: (ansible_distribution_version != '6.10' and ansible_distribution_version != '7.9'
             and ansible_distribution_version != '8.5') and not skip_os_version_check

```
